kind: pipeline
type: kubernetes
name: test

trigger:
  event:
    - push

image_pull_secrets:
  - DOCKER_CONFIG_JSON

steps:
  - name: build-test
    image: harbor.devops.indico.io/indico/drone-builder
    settings:
      username:
        from_secret: harbor_username
      password:
        from_secret: harbor_password
      registry: harbor.devops.indico.io
      repo: harbor.devops.indico.io/indico/virga
      tags:
        - ${DRONE_COMMIT_SHA}.unittest
      squash: true
      experimental: true
    environment:
      DOCKER_BUILDKIT: 1

  - name: test-db
    image: postgres:12-alpine
    detach: true
    environment:
      POSTGRES_DB: indico
      POSTGRES_USER: indico
      POSTGRES_PASSWORD: development

  - name: noct
    image: harbor.devops.indico.io/indico/noct
    detach: true
    environment:
      NOCT_BYPASS_CONFIRMATION: True
      NOCT_BYPASS_APP_ACCESS: True
      POSTGRES_HOST: test-db

  - name: linting
    image: harbor.devops.indico.io/indico/virga:${DRONE_COMMIT_SHA}.unittest
    commands:
      - ./scripts/run_lints.sh
    depends_on:
      - build-test
    when:
      status:
      - failure
      - success

  - name: test
    image: harbor.devops.indico.io/indico/virga:${DRONE_COMMIT_SHA}.unittest
    commands:
      - ./scripts/run_tests.sh
    environment:
      POSTGRES_HOST: test-db
      POSTGRES_DB: indico
      POSTGRES_USER: indico
      POSTGRES_PASSWORD: development
    depends_on:
      - build-test
    when:
      status:
      - failure
      - success

---
kind: secret
name: DOCKER_CONFIG_JSON
get:
  path: tools/drone/devops_harbor_pull_secret
  name: DOCKER_CONFIG_JSON
---
kind: secret
name: harbor_username
get:
  path: tools/drone/harbor-push-token
  name: username
---
kind: secret
name: harbor_password
get:
  path: tools/drone/harbor-push-token
  name: password
