[tool.poetry]
name = "virga"
version = "1.1.1"
description = "Templated adaptable sidecar app generation."
authors = ["thearchitector <elias.gabriel@indico.io>"]

[tool.poetry.dependencies]
python = "^3.7"
click = "^7.1.2"
patch = "^1.16"
requests = "^2.25.1"
python-jose = {extras = ["cryptography"], version = "^3.2.0"}
graphene = "^2.1.8"
orjson = "^3.5.0"
fastapi = "^0.63.0"
SQLAlchemy = "^1.4"
alembic = "^1.5.5"
indico-client = "^4.12.5"

[tool.poetry.dev-dependencies]
asyncpg = "^0.22.0"
pytest = "^6.2.4"
pytest-asyncio = "^0.15.1"
black = "^21.6b0"
mypy = "^0.910"
sqlalchemy2-stubs = "^0.0.2-alpha.4"
types-orjson = "^0.1.1"
types-requests = "^2.25.0"

[tool.poetry.scripts]
virga = "virga._cli.application:virga"

[tool.mypy]
ignore_missing_imports = true
warn_return_any = true
show_column_numbers = true
follow_imports = "silent"
warn_unreachable = true
plugins = "sqlalchemy.ext.mypy.plugin"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
