apiVersion: v1
kind: Secret
metadata:
  name: api-secrets
  namespace: {{- if .Values.defaultNamespace }} {{ .Values.defaultNamespace | default "default" }}{{- else }} default{{- end }}
type: Opaque
stringData:
{{- /*
  # Virga authentication handling
  ATMOSPHERE_COOKIE_SECRET: "{{ .Values.auth.config.atmosphere_cookie_secret }}"
  ATMOSPHERE_TOKEN_SECRET: "{{ .Values.auth.config.atmosphere_token_secret }}"
*/}}
{{- /*
  # postgres
  POSTGRES_PASSWORD: "{{ .Values.postgres.config.password }}"
*/}}
