apiVersion: v1
kind: ConfigMap
metadata:
  name: ui-app-config
  namespace: {{- if .Values.defaultNamespace }} {{ .Values.defaultNamespace | default "default" }}{{- else }} default{{- end }}
data:
  app-config.js: |
    (function() {
      window.indico = {
          {{- /*
          features: {
              inactivityTimeout: {{ (eq (toString .Values.webui.config.inactivityTimeout) "false") | ternary false true }},
              loginOption: {{ hasKey .Values.webui.config "loginOption" }},
          },
          featuresConfig: {
              {{- if kindIs "float64" .Values.webui.config.inactivityTimeout }}
              inactivityTimeout: {{ mul .Values.webui.config.inactivityTimeout 1000 }},
              {{- else if or (ne (hasKey .Values.webui.config "inactivityTimeout") true) .Values.webui.config.inactivityTimeout }}
              inactivityTimeout: 900000,
              {{- end }}
              {{- if .Values.webui.config.loginOption }}
              loginOption: {{ .Values.webui.config.loginOption | quote }},
              {{- end }}
          },
          */}}
          appURLs: {
              {{- /*
              AuthURL: "{{ .Values.auth.config.url }}",
              */}}
              DocsURL: "https://indicodata.ai/docs/",
              HelpURL: "https://indicodata.ai/docs/"
          }
        };
    })();
