kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: read-write
  namespace: {{- if .Values.defaultNamespace }} {{ .Values.defaultNamespace | default "default" }}{{- else }} default{{- end }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 800Gi
