FROM ubuntu:20.04

ENV APP_NAME $app_name
ENV POETRY_HOME=/etc/poetry

# system dependencies
RUN apt update && \
    apt install -y python3.8-dev

COPY . /$app_name
WORKDIR /$app_name

# app dependencies
RUN curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python3 - && \
    . /etc/poetry/env && \
    poetry install --remove-untracked

ENTRYPOINT "/$app_name/scripts/entrypoint.sh"
